/**
 * Modal de création/édition de ressource
 *
 * LOG-01: Référentiel matériel - Création/modification (Admin uniquement)
 * LOG-02: Fiche ressource - Nom, code, photo, couleur, plage horaire
 */

import React, { useState, useEffect } from 'react'
import { X, Save, AlertCircle } from 'lucide-react'
import type { Ressource, RessourceCreate, RessourceUpdate, CategorieRessource } from '../../types/logistique'
import { CATEGORIES_RESSOURCES } from '../../types/logistique'
import { createRessource, updateRessource } from '../../services/logistique'
import { logger } from '../../services/logger'
import { useFocusTrap } from '../../hooks/useFocusTrap'

interface RessourceModalProps {
  ressource?: Ressource // Si défini, mode édition
  onClose: () => void
  onSuccess: () => void
}

const COULEURS_PREDEFINES = [
  '#3B82F6', // blue
  '#10B981', // green
  '#F59E0B', // amber
  '#EF4444', // red
  '#8B5CF6', // violet
  '#EC4899', // pink
  '#F97316', // orange
  '#06B6D4', // cyan
]

/**
 * Modal de création/édition de ressource (Admin uniquement)
 */
export const RessourceModal: React.FC<RessourceModalProps> = ({
  ressource,
  onClose,
  onSuccess,
}) => {
  const isEditMode = !!ressource
  const focusTrapRef = useFocusTrap({ enabled: true, onClose })

  // État du formulaire
  const [formData, setFormData] = useState<RessourceCreate>({
    nom: ressource?.nom || '',
    code: ressource?.code || '',
    categorie: ressource?.categorie || 'gros_outillage',
    couleur: ressource?.couleur || COULEURS_PREDEFINES[0],
    heure_debut_defaut: ressource?.heure_debut_defaut || '08:00',
    heure_fin_defaut: ressource?.heure_fin_defaut || '17:00',
    validation_requise: ressource?.validation_requise ?? true,
    description: ressource?.description || '',
    photo_url: ressource?.photo_url || '',
  })

  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [codeAutoGenerated, setCodeAutoGenerated] = useState(false)

  // Mettre à jour validation_requise selon la catégorie
  useEffect(() => {
    const categorieInfo = CATEGORIES_RESSOURCES[formData.categorie]
    setFormData(prev => ({
      ...prev,
      validation_requise: categorieInfo.validationRequise,
    }))
  }, [formData.categorie])

  // Générer automatiquement le code à partir du nom (uniquement en mode création)
  useEffect(() => {
    // Générer uniquement si:
    // - mode création
    // - nom rempli
    // - code pas encore auto-généré
    // - code vide ou inexistant
    if (!isEditMode && formData.nom.trim() && !codeAutoGenerated && (!formData.code || formData.code.trim() === '')) {
      // Prendre les 3 premiers mots significatifs et créer un code
      const words = formData.nom
        .toUpperCase()
        .replace(/[^A-Z0-9\s]/g, '') // Retirer caractères spéciaux
        .split(/\s+/)
        .filter(w => w.length > 0)
        .slice(0, 3)

      if (words.length > 0) {
        // Prendre les 3-4 premières lettres de chaque mot
        const codeParts = words.map(w => w.substring(0, w.length >= 4 ? 4 : 3))
        const generatedCode = codeParts.join('').substring(0, 15) // Max 15 caractères

        setFormData(prev => ({
          ...prev,
          code: generatedCode,
        }))
        setCodeAutoGenerated(true)
      }
    }
  }, [formData.nom, isEditMode, codeAutoGenerated, formData.code])

  const handleChange = (field: keyof RessourceCreate, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    setError(null)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError(null)

    try {
      // Validation
      if (!formData.nom.trim()) {
        throw new Error('Le nom est obligatoire')
      }
      if (!formData.code.trim()) {
        throw new Error('Le code est obligatoire')
      }
      if (formData.heure_debut_defaut && formData.heure_fin_defaut &&
          formData.heure_debut_defaut >= formData.heure_fin_defaut) {
        throw new Error('L\'heure de début doit être avant l\'heure de fin')
      }

      if (isEditMode && ressource) {
        // Mode édition
        const updateData: RessourceUpdate = {
          nom: formData.nom,
          code: formData.code,
          categorie: formData.categorie,
          couleur: formData.couleur,
          heure_debut_defaut: formData.heure_debut_defaut,
          heure_fin_defaut: formData.heure_fin_defaut,
          validation_requise: formData.validation_requise,
          description: formData.description || undefined,
          photo_url: formData.photo_url || undefined,
        }
        await updateRessource(ressource.id, updateData)
        logger.info('Ressource mise à jour', { ressourceId: ressource.id, nom: formData.nom })
      } else {
        // Mode création
        await createRessource(formData)
        logger.info('Ressource créée', { nom: formData.nom, code: formData.code })
      }

      onSuccess()
    } catch (err: any) {
      const message = err.response?.data?.detail || err.message || 'Une erreur est survenue'
      setError(message)
      logger.error('Erreur lors de la sauvegarde de la ressource', err)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div ref={focusTrapRef} role="dialog" aria-modal="true" aria-labelledby="modal-title" className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <h2 id="modal-title" className="text-xl font-semibold text-gray-900">
            {isEditMode ? 'Modifier la ressource' : 'Nouvelle ressource'}
          </h2>
          <button
            onClick={onClose}
            className="text-gray-600 hover:text-gray-800 transition-colors"
            disabled={loading}
          >
            <X size={24} />
          </button>
        </div>

        {/* Formulaire */}
        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          {/* Erreur */}
          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4 flex items-start gap-3">
              <AlertCircle className="text-red-500 flex-shrink-0" size={20} />
              <p className="text-sm text-red-700">{error}</p>
            </div>
          )}

          <p className="text-sm text-gray-500">Les champs marques <span className="text-red-500">*</span> sont obligatoires</p>

          {/* Nom */}
          <div>
            <label htmlFor="nom" className="block text-sm font-medium text-gray-700 mb-2">
              Nom de la ressource <span className="text-red-500">*</span>
            </label>
            <input
              id="nom"
              type="text"
              value={formData.nom}
              onChange={(e) => handleChange('nom', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="Ex: Grue mobile 50T"
              required
              aria-required="true"
              disabled={loading}
            />
          </div>

          {/* Code */}
          <div>
            <label htmlFor="code" className="block text-sm font-medium text-gray-700 mb-2">
              Code <span className="text-red-500">*</span>
            </label>
            <input
              id="code"
              type="text"
              value={formData.code}
              onChange={(e) => handleChange('code', e.target.value.toUpperCase())}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 font-mono"
              placeholder="Ex: GRUE01"
              required
              aria-required="true"
              disabled={loading}
              maxLength={20}
            />
            <p className="text-xs text-gray-500 mt-1">
              Code unique pour identifier la ressource (max 20 caractères)
            </p>
          </div>

          {/* Catégorie */}
          <div>
            <label htmlFor="categorie" className="block text-sm font-medium text-gray-700 mb-2">
              Catégorie <span className="text-red-500">*</span>
            </label>
            <select
              id="categorie"
              value={formData.categorie}
              onChange={(e) => handleChange('categorie', e.target.value as CategorieRessource)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              required
              aria-required="true"
              disabled={loading}
            >
              {Object.entries(CATEGORIES_RESSOURCES).map(([key, value]) => (
                <option key={key} value={key}>
                  {value.label}
                </option>
              ))}
            </select>
            <p className="text-xs text-gray-500 mt-1">
              {CATEGORIES_RESSOURCES[formData.categorie].validationRequise
                ? '✓ Validation N+1 requise'
                : '○ Validation N+1 optionnelle'}
            </p>
          </div>

          {/* Description */}
          <div>
            <label htmlFor="description" className="block text-sm font-medium text-gray-700 mb-2">
              Description
            </label>
            <textarea
              id="description"
              value={formData.description}
              onChange={(e) => handleChange('description', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="Description détaillée de la ressource..."
              rows={3}
              disabled={loading}
            />
          </div>

          {/* Plage horaire par défaut */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label htmlFor="heure_debut" className="block text-sm font-medium text-gray-700 mb-2">
                Heure début
              </label>
              <input
                id="heure_debut"
                type="time"
                value={formData.heure_debut_defaut}
                onChange={(e) => handleChange('heure_debut_defaut', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                disabled={loading}
              />
            </div>
            <div>
              <label htmlFor="heure_fin" className="block text-sm font-medium text-gray-700 mb-2">
                Heure fin
              </label>
              <input
                id="heure_fin"
                type="time"
                value={formData.heure_fin_defaut}
                onChange={(e) => handleChange('heure_fin_defaut', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                disabled={loading}
              />
            </div>
          </div>

          {/* Couleur */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Couleur d'affichage
            </label>
            <div className="flex gap-2 flex-wrap">
              {COULEURS_PREDEFINES.map((couleur) => (
                <button
                  key={couleur}
                  type="button"
                  onClick={() => handleChange('couleur', couleur)}
                  className={`w-10 h-10 rounded-lg border-2 transition-all ${
                    formData.couleur === couleur
                      ? 'border-gray-900 scale-110'
                      : 'border-gray-300 hover:border-gray-400'
                  }`}
                  style={{ backgroundColor: couleur }}
                  disabled={loading}
                  title={couleur}
                />
              ))}
            </div>
            <div className="mt-2">
              <input
                type="text"
                value={formData.couleur || ''}
                onChange={(e) => handleChange('couleur', e.target.value)}
                className="w-32 px-3 py-1 text-sm border border-gray-300 rounded font-mono"
                placeholder="#3B82F6"
                pattern="^#[0-9A-Fa-f]{6}$"
                disabled={loading}
              />
            </div>
          </div>

          {/* Boutons */}
          <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
              disabled={loading}
            >
              Annuler
            </button>
            <button
              type="submit"
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={loading}
            >
              <Save size={18} />
              <span>{loading ? 'Enregistrement...' : isEditMode ? 'Mettre à jour' : 'Créer'}</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

export default RessourceModal
