"""Application Layer du module Signalements."""

from .dtos import (
    SignalementDTO,
    SignalementCreateDTO,
    SignalementUpdateDTO,
    SignalementListDTO,
    SignalementSearchDTO,
    SignalementStatsDTO,
    ReponseDTO,
    ReponseCreateDTO,
    ReponseUpdateDTO,
    ReponseListDTO,
)
from .use_cases import (
    CreateSignalementUseCase,
    GetSignalementUseCase,
    ListSignalementsUseCase,
    SearchSignalementsUseCase,
    UpdateSignalementUseCase,
    DeleteSignalementUseCase,
    AssignerSignalementUseCase,
    MarquerTraiteUseCase,
    CloturerSignalementUseCase,
    ReouvrirsignalementUseCase,
    GetStatistiquesUseCase,
    GetSignalementsEnRetardUseCase,
    CreateReponseUseCase,
    ListReponsesUseCase,
    UpdateReponseUseCase,
    DeleteReponseUseCase,
    SignalementNotFoundError,
    ReponseNotFoundError,
    InvalidStatusTransitionError,
    AccessDeniedError,
)

__all__ = [
    # DTOs
    "SignalementDTO",
    "SignalementCreateDTO",
    "SignalementUpdateDTO",
    "SignalementListDTO",
    "SignalementSearchDTO",
    "SignalementStatsDTO",
    "ReponseDTO",
    "ReponseCreateDTO",
    "ReponseUpdateDTO",
    "ReponseListDTO",
    # Use Cases
    "CreateSignalementUseCase",
    "GetSignalementUseCase",
    "ListSignalementsUseCase",
    "SearchSignalementsUseCase",
    "UpdateSignalementUseCase",
    "DeleteSignalementUseCase",
    "AssignerSignalementUseCase",
    "MarquerTraiteUseCase",
    "CloturerSignalementUseCase",
    "ReouvrirsignalementUseCase",
    "GetStatistiquesUseCase",
    "GetSignalementsEnRetardUseCase",
    "CreateReponseUseCase",
    "ListReponsesUseCase",
    "UpdateReponseUseCase",
    "DeleteReponseUseCase",
    # Errors
    "SignalementNotFoundError",
    "ReponseNotFoundError",
    "InvalidStatusTransitionError",
    "AccessDeniedError",
]
