"""Application layer du module Interventions."""

from .use_cases import (
    CreateInterventionUseCase,
    GetInterventionUseCase,
    ListInterventionsUseCase,
    UpdateInterventionUseCase,
    PlanifierInterventionUseCase,
    DemarrerInterventionUseCase,
    TerminerInterventionUseCase,
    AnnulerInterventionUseCase,
    DeleteInterventionUseCase,
    AffecterTechnicienUseCase,
    DesaffecterTechnicienUseCase,
    ListTechniciensInterventionUseCase,
    AddMessageUseCase,
    ListMessagesUseCase,
    ToggleRapportInclusionUseCase,
    AddSignatureUseCase,
    ListSignaturesUseCase,
)
from .dtos import (
    CreateInterventionDTO,
    UpdateInterventionDTO,
    PlanifierInterventionDTO,
    DemarrerInterventionDTO,
    TerminerInterventionDTO,
    InterventionResponseDTO,
    InterventionListResponseDTO,
    InterventionFiltersDTO,
    TechnicienResponseDTO,
    AffecterTechnicienDTO,
    MessageResponseDTO,
    CreateMessageDTO,
    SignatureResponseDTO,
    CreateSignatureDTO,
)

__all__ = [
    # Use Cases
    "CreateInterventionUseCase",
    "GetInterventionUseCase",
    "ListInterventionsUseCase",
    "UpdateInterventionUseCase",
    "PlanifierInterventionUseCase",
    "DemarrerInterventionUseCase",
    "TerminerInterventionUseCase",
    "AnnulerInterventionUseCase",
    "DeleteInterventionUseCase",
    "AffecterTechnicienUseCase",
    "DesaffecterTechnicienUseCase",
    "ListTechniciensInterventionUseCase",
    "AddMessageUseCase",
    "ListMessagesUseCase",
    "ToggleRapportInclusionUseCase",
    "AddSignatureUseCase",
    "ListSignaturesUseCase",
    # DTOs
    "CreateInterventionDTO",
    "UpdateInterventionDTO",
    "PlanifierInterventionDTO",
    "DemarrerInterventionDTO",
    "TerminerInterventionDTO",
    "InterventionResponseDTO",
    "InterventionListResponseDTO",
    "InterventionFiltersDTO",
    "TechnicienResponseDTO",
    "AffecterTechnicienDTO",
    "MessageResponseDTO",
    "CreateMessageDTO",
    "SignatureResponseDTO",
    "CreateSignatureDTO",
]
